# Generated by Django 5.1.3 on 2024-11-25 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='country',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='deadline',
        ),
    ]
